spring:
  profiles:
    active: local

  redis:
    port: 6379
    host: localhost

  datasource:
    url: jdbc:h2:tcp://localhost/~/unhaha
    username: sa
    password:
    driver-class-name: org.h2.Driver

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 네이버 로그인 인증 요청 uri
            token-uri: https://nid.naver.com/oauth2.0/token # 토큰을 발급받기 위한 uri
            user-info-uri: https://openapi.naver.com/v1/nid/me # 유저 정보를 받아오기 위한 uri
            user-name-attribute: response
        registration:
          naver:
            client-id: ${client-id} # Client ID
            client-secret: ${client-secret} # Client Secret
            client-name: Naver
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver # Callback URL
            scope:
              - name
              - email
              - nickname
file:
  dir: C:/Users/edgeb/Spring_Study/unhaha/src/main/resources/static/images/userImage/
  article: C:/Users/edgeb/Spring_Study/unhaha/src/main/resources/static/images/article/
  add: file:///Users/edgeb/Spring_Study/unhaha/src/main/resources/static/images/userImage/
  fileArticle: file:///Users/edgeb/Spring_Study/unhaha/src/main/resources/static/images/article/
logging:
  level:
    org.hibernate.SQL: debug